//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diphap.JsNetBridge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diphap.JsNetBridge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///
        ///    window.$dp = window.$dp || {}; window.$dp.shared = window.$dp.shared || {};
        ///
        ///    if (window.$dp.shared.arrayFactory !== undefined) { return; }
        ///
        ///    $dp.shared.arrayFactory = function arrayFactory(ref) {
        ///        /// &lt;signature&gt;
        ///        ///   &lt;summary&gt;this function returns a array with added function &apos;$dpItemFactory&apos; who creates instance of item of array.&lt;/summary&gt;
        ///        ///   &lt;param name=&quot;ref&quot; type=&quot;Function&quot;&gt;ref is factory who creates instance of item of array&lt;/param&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string arrayFactory {
            get {
                return ResourceManager.GetString("arrayFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    window.$dp = window.$dp || {};
        ///    window.$dp.shared = window.$dp.shared || {};
        ///
        ///    if (window.$dp.shared.circularReferenceManagerFactory !== undefined) { return; }
        ///
        ///    window.$dp.shared.circularReferenceManagerFactory = function circularReferenceManagerFactory(sameIntance) {
        ///        /// &lt;signature&gt;
        ///        ///   &lt;summary&gt;Factory gives un new instance of Function that handles the circular reference objects.&lt;/summary&gt;
        ///        ///   &lt;param name=&quot;sameIntance&quot; type=&quot;bool&quot;&gt;If sameIn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string circularReferenceManagerFactory {
            get {
                return ResourceManager.GetString("circularReferenceManagerFactory", resourceCulture);
            }
        }
    }
}
